language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r kchung-spring2-webservice
  - mkdir -p deploy
  - mv kchung-spring2-webservice.zip deploy/kchung-spring2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kchung1995-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - kchung1995@gmail.com
      - kchung1995@naver.com
